REQUIRED_TAGS = ["Project", "Environment", "Owner"]

DEFAULT_REGION = "us-east-1"
DEFAULT_ACCOUNT_ID = "000000000000"
DEFAULT_STOPPED_DAYS = 14
DEFAULT_ENDPOINT_URL = "http://localhost:4566"

REPORT_JSON_PATH = "report.json"
REPORT_MARKDOWN_PATH = "report.md"
EBS_GB_MONTH_USD = 0.08
STOPPED_EC2_MONTHLY_ESTIMATE_USD = 3.00
UNUSED_EIP_MONTHLY_ESTIMATE_USD = 3.60
MISSING_TAG_COST_USD = 0.00
